packages/eslint-plugin/lib/rules/element-newline.js, packages/eslint-plugin/tests/rules/element-newline.test.js
=> handle missing closing tag in `element-newline` (fixes #30)

.github/workflows/main.yml
`test:all` already includes `npm run test`.
=> CI: Remove redundant test run

docs/rules/require-closing-tags.md, packages/eslint-plugin/lib/rules/require-closing-tags.js, packages/eslint-plugin/tests/rules/require-closing-tags.test.js
=> feat: [require-closing-tags] Add allowSelfClosingCustom options (fix #99)

docs/rules/no-extra-spacing-attrs.md, packages/eslint-plugin/lib/rules/no-extra-spacing-attrs.js, packages/eslint-plugin/tests/rules/no-extra-spacing-attrs.test.js
This option disallows missing space between attributes.
Closes #119
=> Add option disallowMissing to `no-extra-spacing-attrs` rule

docs/rules/require-meta-viewport.md
Hi! 👋 
If I'm correct, the examples on this page are mixed up, given that the current incorrect example is the correct one. This PR serves to swap them, if you think it's relevant. 
Thanks! 😄
=> fix(docs): swap the correct and incorrect examples for `require-meta-viewport`

docs/rules.md
noticed a minor issue in the docs where the `require-attrs` link seems to have been copied from `no-restricted-attrs` without updating the name
=> docs: fix `require-attrs` name in rule list

docs/rules/no-restricted-attr-values.md
Just copied from the docs page to my shared ESLint config and noticed the error :)
=> fix: correct `not-restricted-attr-values` docs title

packages/eslint-plugin/lib/rules/require-doctype.js, packages/eslint-plugin/tests/rules/require-doctype.test.js
=> feat: skip check when html tag does not exists

docs/rules/sort-attrs.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/sort-attrs.js, packages/eslint-plugin/tests/rules/sort-attrs.test.js
=> feat: add sort-attrs (fixes #92)

docs/rules/id-naming-convention.md, packages/eslint-plugin/lib/rules/id-naming-convention.js, packages/eslint-plugin/tests/rules/id-naming-convention.test.js
hey there! i ran into a case where `id-naming-convention` rule would be helpful, but the provided options are too strict to easily adopt (it's a large repo with multiple competing standards). this updates the rule to support a custom regex, which should hopefully make it flexible enough to cover any cases which deviate from the common standards
=> feat: add "regex" option to `id-naming-convention`

package.json, packages/website/.posthtmlrc.js, packages/website/src/components/nav.html
Thank you for this plugin.
This is just a minor spelling correction, "accesibility" → "accessibility".
Not sure why cspell didn't catch this. 🤷‍♂️
=> docs: correct spelling of "accessibility"

.cspell.json, docs/rules/require-closing-tags.md, packages/eslint-plugin/lib/rules/require-closing-tags.js, packages/eslint-plugin/tests/rules/require-closing-tags.test.js
Hey there! I ran into an issue using `require-closing-tags` with the `selfClosing: "always"` option where non-void elements were not being checked correctly. For example:
```js
"@html-eslint/require-closing-tags": ["error", { "selfClosing": "always" }],
```
```html
<div />
```
In this case `<div />` is incorrect (`div` is not a void element and cannot self-close), but the linter would not catch it.
The scope of this fix ended up being larger than expected: custom tags which did not use `-` as part of their naming convention and tags in a foreign context were not explicitly supported, and instead seemed to be handled via this bug. To compensate, I've re-implemented a version of the stack-based approach for handling foreign context seen in earlier implementations of the rule, and added a …
=> feat: better `require-closing-tags` support

docs/getting-started.md, integration-test-projects/v8/eslint.config.js
Fixes #189.
Added "or if using `require(..);`" example on each section, but feels a little bit redundant. Didn't know if I should keep them or not.
=> docs: improve flat config examples

docs/rules/no-extra-spacing-attrs.md, packages/eslint-plugin/lib/rules/no-extra-spacing-attrs.js, packages/eslint-plugin/tests/rules/no-extra-spacing-attrs.test.js
This adds two things to `no-extra-spacing-attrs`:
- It adds a `disallowTabs` option to enforce using only spaces inside a tag
- It checks for extra spaces between the tag start and the tag end, whereas the current version only checks for extra spaces before the tag end if the tag has attributes or is self-closing
Because this rule can now have an effect when a tag has no attributes, in the future may want to rename the rule to just `no-extra-spacing`... Just a thought!
Thanks! :)
=> feat: add test for tabs in no-extra-spacing-attrs

README.md, packages/website/src/components/home.html
=> docs: add docs about lint javascript inside html

.vscode/settings.json, docs/rules.md, docs/rules/no-extra-spacing-text.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/no-extra-spacing-text.js, packages/eslint-plugin/lib/types.d.ts, packages/eslint-plugin/tests/rules/no-extra-spacing-text.test.js
This adds a rule to prevent unnecessary whitespace in text.
=> feat: adds no-extra-spacing-text

docs/rules/element-newline.md, packages/eslint-plugin/lib/configs/recommended.js, packages/eslint-plugin/lib/rules/element-newline.js, packages/eslint-plugin/tests/rules/element-newline.test.js, packages/website/src/components/header/header.html
- Adds additional error messages to `element-newline`, so that it specifies whether a space is needed between a tag and its content or between two sibling elements
- Adds an `inline` option to `element-newline`, indicating that the specified elements can be on the same line when they are siblings
=> feat: adds `inline` option to element-newline; fixes #210

packages/eslint-plugin/lib/rules/lowercase.js, packages/eslint-plugin/lib/rules/no-inline-styles.js, packages/eslint-plugin/lib/rules/utils/visitors.js, packages/eslint-plugin/lib/types.d.ts, packages/eslint-plugin/package.json, packages/eslint-plugin/tests/rules/lowercase.test.js, packages/eslint-plugin/tests/rules/no-inline-styles.test.js, packages/template-parser/lib/traverser.js, packages/template-parser/lib/types.d.ts, packages/template-parser/tests/template-parser.test.js
=> feat: support linting html in template literals in lowercase

packages/eslint-plugin/lib/rules/id-naming-convention.js, packages/eslint-plugin/lib/rules/utils/node.js, packages/eslint-plugin/tests/rules/id-naming-convention.test.js
=> feat: support linting html in template literals in id-naming-convention

packages/eslint-plugin/lib/rules/no-abstract-roles.js, packages/eslint-plugin/tests/rules/no-abstract-roles.test.js
=> feat: support linting html in template literals in no-abstract-roles

packages/eslint-plugin/lib/rules/no-extra-spacing-attrs.js, packages/eslint-plugin/tests/rules/no-extra-spacing-attrs.test.js, packages/parser/package.json, packages/template-parser/lib/template-parser.js, packages/template-parser/package.json, yarn.lock
=> feat: support linting html in template literals in no-extra-spacing-attrs

packages/eslint-plugin/lib/rules/element-newline.js, packages/eslint-plugin/lib/rules/no-duplicate-id.js, packages/eslint-plugin/lib/rules/no-extra-spacing-text.js, packages/eslint-plugin/lib/rules/no-multiple-empty-lines.js, packages/eslint-plugin/lib/rules/no-multiple-h1.js, packages/eslint-plugin/lib/rules/no-skip-heading-levels.js, packages/eslint-plugin/lib/rules/no-trailing-spaces.js, packages/eslint-plugin/lib/rules/require-li-container.js, packages/eslint-plugin/lib/rules/utils/node.js, packages/eslint-plugin/lib/types.d.ts, packages/eslint-plugin/package.json, packages/eslint-plugin/tests/rules/no-extra-spacing-text.test.js, packages/eslint-plugin/tests/rules/no-multiple-empty-lines.test.js, packages/eslint-plugin/tests/rules/no-trailing-spaces.test.js, packages/parser/lib/node-types.js, packages/parser/lib/parser.js, packages/parser/lib/visitor-keys.js, packages/parser/package.json, packages/template-parser/lib/template-parser.js, packages/template-parser/package.json, yarn.lock
Applying template-parser to the rules
- no-extra-spacing-text
- no-multiple-empty-lines
- no-trailing-spaces
=> feat: support linting html in template literals in no-extra-spacing-text

packages/eslint-plugin/lib/rules/indent.js, packages/eslint-plugin/tests/rules/indent.test.js
=> fix: fix base indent in template literals

.prettierignore, docs/getting-started.md, packages/website/.eslintrc.js, packages/website/scripts/generates/renderer.js, packages/website/src/common.css, packages/website/src/components/footer.html, packages/website/src/components/header/header.html, packages/website/src/components/header/nav.html, packages/website/src/components/home.html, packages/website/src/components/layout.html, packages/website/src/components/nav-list.html, packages/website/src/components/nav.html, packages/website/src/components/playground.html, packages/website/src/components/template.html, packages/website/src/index.html, packages/website/src/playground.html, packages/website/src/scripts/playground/view.js, packages/website/src/templates/rule.html
=> docs: add docs about lint html in js template literal

docs/rules.md, docs/rules/prefer-https.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/prefer-https.js, packages/eslint-plugin/lib/rules/utils/node.js, packages/eslint-plugin/tests/rules/prefer-https.test.js
=> feat: add prefer-https rule

.cspell.json, docs/rules.md, docs/rules/require-input-label.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/require-input-label.js, packages/eslint-plugin/lib/rules/utils/node.js, packages/eslint-plugin/lib/types/ast.d.ts, packages/eslint-plugin/lib/types/rule.d.ts, packages/eslint-plugin/tests/rules/require-input-label.test.js
=> feat: add require-input-label rule

docs/rules/require-form-method.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/require-form-method.js, packages/eslint-plugin/tests/rules/require-form-method.test.js
=> feat: add require-form-method rule

docs/rules.md, docs/rules/no-heading-inside-button.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/no-heading-inside-button.js, packages/eslint-plugin/tests/rules/no-heading-inside-button.test.js
=> feat: add no-heading-inside-button rule

docs/rules/no-nested-interactive.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/no-nested-interactive.js, packages/eslint-plugin/tests/rules/no-nested-interactive.test.js
=> feat: add no-nested-interactive rule

docs/rules.md, docs/rules/max-element-depth.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/max-element-depth.js, packages/eslint-plugin/tests/rules/max-element-depth.test.js
=> feat: add max-element-depth rule

docs/rules/sort-attrs.md
Added missing `"` after `"style` at lines 45 and 51.
=> fix(docs/rules/sort-attrs.md): fix typo

packages/eslint-plugin/lib/rules/indent/indent.js, packages/eslint-plugin/tests/rules/indent.test.js
Fixes #264
Add the missing handling inside the file `indent.js` to manage the closing tags for script and style
Two tests added inside `indent.test.js` to verify:
- if a valid `</script>` tag and `</style>` tag passes without errors
- if an invalid `</script>` tag and `</style>` tag (with incorrect indentation e.g. two extra spaces) triggers errors
=> fix: indentation rules for script and style tags

docs/rules/attrs-newline.md, packages/eslint-plugin/lib/rules/attrs-newline.js, packages/eslint-plugin/tests/rules/attrs-newline.test.js
Good day,
This PR closes #303 
It was pretty easy to do, as it's just removing the part of the code that is responsible for handling the "reverse" validation of fewer attributes.
Hope I didn't forget anything :)
=> fix: disable validation of fewer attributes in `attrs-newline`

packages/eslint-plugin/lib/rules/use-baseline.js, packages/eslint-plugin/tests/rules/use-baseline.test.js
=> fix: report location in use-baseline

.github/workflows/main.yml, docs/getting-started.md, docs/integrating-template-engine.md, package.json, packages/eslint-plugin/lib/index.js, packages/eslint-plugin/lib/languages/html-language.js, packages/eslint-plugin/lib/languages/html-source-code.js, packages/eslint-plugin/lib/languages/html-traversal-step.js, packages/eslint-plugin/package.json, packages/eslint-plugin/tests/inline-disable.test.js, packages/eslint-plugin/tests/languages/html-language.test.js, packages/eslint-plugin/tests/languages/html-source-code.test.js, packages/eslint-plugin/tests/rule-tester.js, packages/eslint-plugin/tests/rules/indent.test.js, packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js, packages/integration-test/fixtures/eslint-v9-language/.yarnrc.yml, packages/integration-test/fixtures/eslint-v9-language/eslint.config.js, packages/integration-test/fixtures/eslint-v9-language/html/invalid.html, packages/integration-test/fixtures/eslint-v9-language/html/valid.html, packages/integration-test/lib/test-utils.js, packages/integration-test/tests/integration.test.js, packages/parser/lib/index.js, packages/parser/package.json, packages/template-parser/package.json, packages/types/package.json, packages/website/src/scripts/playground/linter.js, turbo.json, yarn.lock
=> feat: implement language plugin

packages/eslint-plugin/lib/rules/no-trailing-spaces.js, packages/eslint-plugin/tests/rules/no-trailing-spaces.test.js
https://html-eslint.org/playground#eyJjb2RlIjoiaHRtbGA8ZGl2PiAgXG4gICAgICAgIDxzcGFuPlxuICAgIDwvc3Bhbj5cbiAgICA8L2Rpdj5cbmBcbiIsImNvbmZpZyI6eyJydWxlcyI6eyJAaHRtbC1lc2xpbnQvbm8tdHJhaWxpbmctc3BhY2VzIjoiZXJyb3IifX0sImxhbmd1YWdlIjoiamF2YXNjcmlwdCJ9
Fixed bug reporting incorrect location when used with template expression.
=> fix: crash with template expression in no-trailing-spaces

docs/rules.md, packages/eslint-plugin/lib/rules/require-open-graph-protocol.js
None.
This PR fixes the `meta.docs.description` property content of rule `require-open-graph-protocol`.
=> fix: correct rule `require-open-graph-protocol` description

docs/rules/max-element-depth.md
- Addresses an existing open issue: fixes #000
Trivial typo
=> docs: fix typo in max-element-depth

packages/eslint-plugin/lib/rules/require-img-alt.js, packages/eslint-plugin/tests/rules/require-img-alt.test.js
- Addresses an existing open issue: closes #349 
Enhances the require-img-alt rule by adding an auto-fix suggestion that inserts an empty alt="" attribute when <img> elements are missing the alt attribute.
Changes Made
* Added auto-fix suggestion: When an <img> tag lacks an alt attribute, the rule now provides a suggestion to insert alt=""
Enhanced error reporting: Uses ESLint's suggest property to offer quick fixes
Comprehensive test coverage: Added test cases covering both standalone HTML and template literal contexts
* Test Cases
Before (Invalid):
html<img src="logo.png">
After (Suggested Fix):
html<img src="logo.png" alt="">
* Features
Works with self-closing and regular <img> tags
Supports substitute attributes (configurable via options)
Compatible with template literals
Maintains …
=> feat: add auto-fix suggestion for require-img-alt rule

packages/eslint-plugin/lib/rules/lowercase.js, packages/eslint-plugin/tests/rules/lowercase.test.js
- Addresses an existing open issue: fixes #350
=> fix: ignore checking tag names in svg in lowercase

packages/eslint-plugin/lib/rules/indent/indent.js, packages/eslint-plugin/lib/rules/no-duplicate-id.js, packages/eslint-plugin/lib/rules/no-duplicate-in-head.js, packages/eslint-plugin/lib/rules/no-multiple-empty-lines.js, packages/eslint-plugin/lib/rules/no-trailing-spaces.js, packages/eslint-plugin/lib/rules/utils/template-cache.js, packages/eslint-plugin/lib/rules/utils/visitors.js
Adding per-node caching of parse results gives a **94% performance improvement** in my project. Before, the rules collectively took ~21s. Now, they take just ~1.2s.
Before:
```
TIMING=all yarn eslint --stats "**/*.{js,jsx,ts,tsx,mjs,cjs,mts,cts}" | grep "@html-eslint/"
@html-eslint/no-positive-tabindex                                         |   723.208 |     3.0%
@html-eslint/require-lang                                                 |   721.106 |     3.0%
@html-eslint/no-empty-headings                                            |   718.906 |     3.0%
@html-eslint/no-extra-spacing-attrs                                       |   714.442 |     3.0%
@html-eslint/quotes                                                       |   714.293 |     3.0%
@html-eslint/no-script-style-type …
```
=> refactor: add cache for template literal parsing

packages/eslint-plugin/lib/rules/indent/indent.js, packages/eslint-plugin/lib/rules/no-duplicate-id.js, packages/eslint-plugin/lib/rules/no-duplicate-in-head.js, packages/eslint-plugin/lib/rules/no-multiple-empty-lines.js, packages/eslint-plugin/lib/rules/no-trailing-spaces.js, packages/eslint-plugin/lib/rules/utils/template-literal.js, packages/eslint-plugin/lib/rules/utils/visitors.js, packages/eslint-plugin/tests/rules/no-duplicate-id.test.js, packages/eslint-plugin/tests/rules/no-trailing-spaces.test.js, packages/eslint-plugin/tests/rules/utils/template-literal.test.js, packages/template-parser/lib/index.js, packages/template-parser/lib/template-parser.js, packages/template-parser/lib/traverser.js
=> refactor: cached parse template literal

docs/rules/quotes.md
- also, align option notation style to ESLint
- Addresses an existing open issue: fixes #394
=> docs(rule: quote): disclaimer enforceTemplatedAttrValue implicitly bans bare templated attributes, clarify object option

packages/eslint-plugin/lib/rules/no-duplicate-attrs.js, packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js
- Addresses an existing open issue: fixes #392
=> fix: ignore attribute key with templates

.cspell.json, docs/rules/no-ineffective-attrs.md, packages/eslint-plugin/lib/rules/index.js, packages/eslint-plugin/lib/rules/no-ineffective-attrs.js, packages/eslint-plugin/lib/rules/utils/node.js, packages/eslint-plugin/tests/rules/no-ineffective-attrs.test.js
- Addresses an existing open issue: fixes #346
=> feat: add new rule no-ineffective-attrs

packages/eslint-plugin/lib/rules/lowercase.js, packages/eslint-plugin/tests/rules/lowercase.test.js, packages/website/src/scripts/playground/helpers.js
- Fixes #410
This commit adds detection and fixers of not-lowercase doctypes in documents, eg. `<!DOCTYPE html>`, `<!doctype HTML>`, or any other capitalization besides the all-lowercased `<!doctype html>`.
I originally wanted to condense the changes to the rule in a single generalized `check()` function, but that ended up feeling kludgy because of the different shape of `Doctype` versus the existing assumptions for the input `Tag | StyleTag | ScriptTag` types. As a result, there is some duplicated code in my implementation here--I'd be happy to clean that up if there is a more ideal structure you'd like to see.
=> feat: support linting doctype in lowercase

packages/eslint-plugin/package.json, packages/parser/package.json, packages/template-parser/package.json, packages/template-syntax-parser/package.json
- Addresses an existing open issue: fixes #420
=> fix: fix @html-eslint/types deps
