yeonjuan/html-eslint

- packages/eslint-plugin/lib/rules/require-doctype.js
- packages/eslint-plugin/tests/rules/require-doctype.test.js
> fix unexpected autofix result in `require-doctype` (ref #28)

- README.md
> add docs about vscode configuration (fixes #27)

- packages/eslint-plugin/tests/rules/indent.test.js
- packages/parser/lib/ast-converter/ast-converter.js
- packages/parser/lib/ast-converter/node-converter.js
- packages/parser/tests/__snapshots__/parser.test.js.snap
- packages/parser/tests/ast-converter/__snapshots__/node-converter.test.js.snap
- packages/parser/tests/parser.test.js
> handle null node correctly (fixes #31)

- docs/rules/no-extra-spacing-attrs.md
It seems that incorrect cod looks like correct one
> Fix typos in no-extra-spacing-attrs.md

- packages/eslint-plugin/tests/rules/indent.test.js
- packages/parser/lib/postprocessor/postprocessor.js
- packages/parser/tests/__snapshots__/parser-template.test.js.snap
- packages/parser/tests/parser-template.test.js
> fix: handle template parsing error (fixes #58)

- packages/eslint-plugin/lib/rules/indent.js
- packages/eslint-plugin/tests/rules/indent.test.js
> fix: [indent] handle attributes indent

- packages/eslint-plugin/tests/rules/require-closing-tags.test.js
- packages/parser/lib/extensions/location-info/parser-mixin.js
> fix: [parser] use case-insensitive comparison on tag name

- docs/all-rules.md
- docs/rules/element-newline.md
- docs/rules/no-duplicate-attrs.md
- docs/rules/quotes.md
- docs/rules/require-img-alt.md
- packages/eslint-plugin/lib/rules/require-meta-charset.js
Hello, thank you for your work, good job!
I setting up the plugin and noticed some typos. This PR fixes it.
> Fix some typos in docs

- packages/eslint-plugin/lib/rules/indent.js
- packages/eslint-plugin/tests/rules/indent.test.js
- packages/eslint-plugin/tests/rules/require-button-type.test.js
- packages/eslint-plugin/tests/rules/require-img-alt.test.js
- packages/eslint-plugin/tests/rules/require-lang.test.js
- packages/parser/jest.config.js
- packages/parser/lib/common/location.js
- packages/parser/lib/postprocessor/utils.js
- packages/parser/setup-jest.js
- packages/parser/tests/__snapshots__/parser-template.test.js.snap
- packages/parser/tests/__snapshots__/parser.test.js.snap
- packages/parser/tests/parser.test.js
> fixes: [indent] handle indent for nodes in same line (ref #93)

- docs/rules/quotes.md
- packages/eslint-plugin/lib/rules/quotes.js
- packages/eslint-plugin/tests/rules/quotes.test.js
> fix: [quotes] handle quotes in the attribute value (fixes #95)

- packages/eslint-plugin/tests/rules/indent.test.js
- fixes #102 
- Add test cases to confirm the issue is fixed.
> fix: [indent] add test cases (fixes #102)

- docs/rules/no-extra-spacing-attrs.md
- packages/eslint-plugin/lib/rules/no-extra-spacing-attrs.js
- packages/eslint-plugin/lib/rules/utils/node-utils.js
- packages/eslint-plugin/lib/types.d.ts
- packages/eslint-plugin/tests/rules/no-extra-spacing-attrs.test.js
> feat: [no-extra-spacing-attrs] Add enforceBeforeSelfClose options

- packages/eslint-plugin/package-lock.json
- packages/eslint-plugin/package.json
- packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js
- packages/parser/package-lock.json
- packages/parser/package.json
> fix: handle CRLF (fixes #110)

- README.md
- docs/getting-started.md
- packages/eslint-plugin/README.md
- packages/website/next.config.js
- packages/website/utils/docs.ts
> docs: fix broken links

- docs/rules.md
- docs/rules/require-attrs.md
- packages/eslint-plugin/lib/rules/index.js
- packages/eslint-plugin/lib/rules/require-attrs.js
- packages/eslint-plugin/tests/rules/require-attrs.test.js
> feat: add require-attrs (fixes #126)

- packages/eslint-plugin/lib/rules/indent.js
- packages/eslint-plugin/tests/rules/indent.test.js
> fix: [indent] Handle script, style indent (fixes #129)

- docs/rules/element-newline.md
- packages/eslint-plugin/lib/rules/element-newline.js
- packages/eslint-plugin/tests/rules/element-newline.test.js
> feat: add skip option to element-newline (fixes #131)

- docs/rules/require-img-alt.md
- packages/eslint-plugin/lib/rules/require-img-alt.js
- packages/eslint-plugin/tests/rules/require-img-alt.test.js
> feat: add substitute option in require-img-alt (fixes #134)

- package-lock.json
- packages/eslint-plugin/tests/rules/no-extra-spacing-attrs.test.js
- packages/parser/package.json
> fix: handle bare attributes in no-extra-spacing-attrs (fixes #137)

- package-lock.json
- packages/website/components/Editor/Editor.tsx
- packages/website/types.d.ts
- packages/website/utils/linter.ts
> fix: playground errors

- .github/workflows/sementic-pr.yml
- #147
- Add github action for checking pr title
> ci: add semantic pr check action

- docs/getting-started.md
- packages/eslint-plugin/lib/index.js
- packages/eslint-plugin/package.json
- packages/website/package.json
- yarn.lock
> feat: support flat config

- docs/rules/id-naming-convention.md
- packages/eslint-plugin/lib/rules/id-naming-convention.js
- packages/eslint-plugin/tests/rules/id-naming-convention.test.js
See https://github.com/yeonjuan/html-eslint/issues/180
> feat: add regexp flags support for id-naming-convention

- packages/parser/lib/index.js
- packages/parser/lib/meta.js
- packages/parser/package.json
- packages/parser/tsconfig.build.json
> fix: export parser meta

- packages/website/package.json
- packages/website/scripts/generates/sitemap.js
- packages/website/scripts/sitemap.js
- Add sitemap generating script
> chore: add sitemap.xml generating script

- .github/workflows/main.yml
- packages/website/.eslintignore
- packages/website/src/components/footer.html
- packages/website/src/components/header/header.html
- packages/website/src/components/header/nav.html
- packages/website/src/components/home.html
- packages/website/src/components/layout.html
- packages/website/src/components/nav-list.html
- packages/website/src/components/nav.html
> ci: add lint

- packages/eslint-plugin/lib/rules/attrs-newline.js
- packages/eslint-plugin/tests/rules/attrs-newline.test.js
> feat: support linting html in template literals in attrs-newline

- .cspell.json
- packages/eslint-plugin/lib/rules/attrs-newline.js
- packages/eslint-plugin/lib/rules/element-newline.js
- packages/eslint-plugin/lib/rules/lowercase.js
- packages/eslint-plugin/lib/rules/no-inline-styles.js
- packages/eslint-plugin/lib/rules/utils/visitors.js
- packages/eslint-plugin/tests/rules/element-newline.test.js
> feat: support linting html in template literals in element-newline

- packages/eslint-plugin/lib/rules/no-duplicate-attrs.js
- packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js
> feat: support linting html in template literals in no-duplicate-attrs

- packages/eslint-plugin/lib/rules/indent.js
- packages/eslint-plugin/lib/rules/utils/node.js
- packages/eslint-plugin/lib/types.d.ts
- packages/eslint-plugin/tests/rules/indent.test.js
- packages/template-parser/lib/template-parser.js
> feat: support linting html in template literals in indent

- docs/rules/indent.md
- packages/eslint-plugin/lib/rules/indent/indent-level.js
- packages/eslint-plugin/lib/rules/indent/indent.js
- packages/eslint-plugin/lib/rules/indent/index.js
- packages/eslint-plugin/tests/rules/indent.test.js
> feat: add options to set indent level based on node type

- packages/eslint-plugin/lib/rules/indent/indent.js
- packages/eslint-plugin/lib/rules/utils/node.js
- packages/eslint-plugin/tests/rules/indent.test.js
- packages/website/src/scripts/playground/linter.js
> fix: nest indent bugs in template literal

- .cspell.json
- docs/rules.md
- docs/rules/no-invalid-role.md
- packages/eslint-plugin/lib/rules/index.js
- packages/eslint-plugin/lib/rules/no-invalid-role.js
- packages/eslint-plugin/tests/rules/no-invalid-role.test.js
> feat: add no-invalid-role rule

- docs/rules/no-restricted-attr-values.md
Looks like https://github.com/yeonjuan/html-eslint/pull/259 was merged in despite a failing Prettier check.
> fix: prettier issue introduced in #259

- .cspell.json
- docs/rules.md
- docs/rules/require-explicit-size.md
- packages/eslint-plugin/lib/rules/index.js
- packages/eslint-plugin/lib/rules/require-explicit-size.js
- packages/eslint-plugin/tests/rules/require-explicit-size.test.js
> feat: add require-explicit-size rule

- packages/eslint-plugin/lib/rules/element-newline.js
- packages/eslint-plugin/tests/rules/element-newline.test.js
> fix: handle CRLF in element-newline

- packages/eslint-plugin/lib/rules/no-duplicate-attrs.js
- packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js
> fix: check case-insensitively in no-duplicate-attrs

- packages/website/src/scripts/playground/app.js
- packages/website/src/scripts/playground/linter.js
- packages/website/src/scripts/playground/model.js
> chore: add support parserOptions in playground

- packages/eslint-plugin/lib/rules/require-button-type.js
- packages/eslint-plugin/lib/types/rule.ts
- packages/eslint-plugin/tests/rules/require-button-type.test.js
> feat: add fix and suggest in require-button-type

- packages/eslint-plugin/lib/rules/no-duplicate-attrs.js
- packages/eslint-plugin/tests/rules/no-duplicate-attrs.test.js
> feat: add suggestion fixer in no-duplicate-attrs

- .cspell.json
- docs/rules.md
- docs/rules/use-baseline.md
- packages/eslint-plugin/lib/configs/recommended.js
- packages/eslint-plugin/lib/rules/index.js
- packages/eslint-plugin/lib/rules/use-baseline.js
- packages/eslint-plugin/tests/rules/use-baseline.test.js
> feat: implement use-baseline

- packages/eslint-plugin/lib/rules/indent/indent.js
- packages/eslint-plugin/tests/rules/indent.test.js
> fix: tagChildrenIndent does not work on script, style

- docs/rules.md
- packages/eslint-plugin/lib/rules/require-attrs.js
- packages/eslint-plugin/lib/types/rule.ts
- packages/eslint-plugin/tests/rules/require-attrs.test.js
- Addresses an existing open issue: fixes #326
> feat: implement autofix in require-attrs

- packages/eslint-plugin/lib/rules/no-invalid-role.js
- packages/eslint-plugin/tests/rules/no-invalid-role.test.js
- Addresses an existing open issue: fixes #334
> fix: handle template expression in no-invalid-role

- packages/eslint-plugin/lib/rules/quotes.js
- packages/eslint-plugin/tests/rules/quotes.test.js
- Addresses an existing open issue: fixes #333
> fix: handle template expression in quotes

- packages/eslint-plugin/lib/index.js
- packages/eslint-plugin/lib/languages/html-language.js
- packages/eslint-plugin/lib/languages/html-source-code.js
- packages/eslint-plugin/tests/languages/html-language.test.js
- packages/eslint-plugin/tests/languages/html-source-code.test.js
- Addresses an existing open issue: fixes #000
> fix: export languages type & remove eslint require

- packages/eslint-plugin/lib/rules/indent/indent.js
- packages/eslint-plugin/lib/rules/no-duplicate-class.js
- packages/eslint-plugin/lib/rules/no-invalid-role.js
- packages/eslint-plugin/lib/rules/no-multiple-empty-lines.js
- packages/eslint-plugin/lib/rules/quotes.js
- packages/eslint-plugin/lib/rules/require-form-method.js
- packages/eslint-plugin/lib/rules/utils/node.js
- packages/template-syntax-parser/package.json
- packages/types/lib/ast.d.ts
- packages/types/lib/html-ast.d.ts
- packages/types/lib/js-ast.d.ts
- packages/types/package.json
- yarn.lock
- Addresses an existing open issue: fixes #357
> fix: wrong dependency 

- packages/integration-test/lib/test-utils.js
- Addresses an existing open issue: fixes #000
> chore: fix integration test yarn version

- docs/rules.md
- packages/eslint-plugin/lib/rules/max-element-depth.js
- packages/eslint-plugin/lib/rules/no-extra-spacing-text.js
- Addresses an existing open issue: fixes #354
> fix: wrong rule category

- docs/rules/quotes.md
- packages/eslint-plugin/lib/rules/quotes.js
- packages/eslint-plugin/tests/rules/quotes.test.js
- Addresses an existing open issue: fixes #384
> feat: add enforceTemplatedAttrValue option on quotes

- .cspell.json
- docs/integrating-template-engine.md
- packages/eslint-plugin/lib/languages/html-language.js
- packages/eslint-plugin/lib/rules/element-newline.js
- packages/eslint-plugin/lib/rules/no-duplicate-attrs.js
- packages/eslint-plugin/lib/rules/utils/settings.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/tests/languages/html-language.test.js
- packages/eslint-plugin/tests/rules/element-newline.test.js
- packages/eslint-plugin/tests/rules/indent.test.js
- packages/parser/lib/options.js
- packages/parser/lib/types.ts
- packages/parser/lib/visitor-keys.js
- packages/parser/package.json
- packages/template-parser/lib/traverser.js
- packages/template-parser/package.json
- packages/types/package.json
- yarn.lock
- Addresses an existing open issue: fixes #381
> feat: add rawContentTags options
